services:
  web:
    build:
      context: .
      args:
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        IMAGEKIT_PRIVATE_KEY: ${IMAGEKIT_PRIVATE_KEY}
        NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: ${NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY}
        NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: ${NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
        ENCRYPTION_KEY: ${ENCRYPTION_KEY}
        MONGO_DB_URL: ${MONGO_DB_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_DATABASE: encryptohub
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: